name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: windows10
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      # - name: Install rsync ğŸ“š
        # run: |
          # npm install rsync

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install source-map-url
          # npm install eslint-import-resolver-webpack
          # npm install react-navigation
          npm install
          # npm install fund
          # npm fund
          npm run build
          # npm start

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: deploy # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.